x-airflow-common:
  &airflow-common
  image: hubdocker.decoded.ir/lake/lakeflow:base
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER:-postgres}:${PG_PASSWORD:-password}@catalog_pg:5432/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${PG_USER:-postgres}:${PG_PASSWORD:-password}@catalog_pg:5432/airflow
    AIRFLOW__CELERY__BROKER_URL: amqp://rabbit:password@rabbitmq:5672/vhost
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://lakeflow_api_server:8080/execution/'
    AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
    AIRFLOW_PROJ_DIR: '/codebase/infrastructure/airflow'
    AIRFLOW_HOME: './infrastructure/airflow'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    AIRFLOW_CONFIG: '/codebase/infrastructure/airflow/config/airflow.cfg'
  volumes:
    - ./infrastructure/airflow/dags:/codebase/resources/airflow/dags
    - ./infrastructure/airflow/config:/codebase/resources/airflow/config
    - ./infrastructure/airflow/logs:/codebase/resources/airflow/logs
    - ./resources/config.yml:/codebase/resources/config.yml
    - ./infrastructure/airflow/plugins:/opt/airflow/plugins
    - ./lake/pages:/codebase/lake/pages
  user: airflow
  depends_on:
    &airflow-common-depends-on
    rabbitmq:
      condition: service_healthy
  networks:
    - lake_net
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: vhost
    networks:
      - lake_net

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    container_name: lakeflow_api_server
    hostname: lakeflow_api_server
    restart: always
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - lake_net

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - lake_net
  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - lake_net

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    restart: always
    ports:
        - "5252:5252"
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    depends_on:
      <<: *airflow-common-depends-on
      airflow-apiserver:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks:
      - lake_net

    
  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - lake_net


  airflow-init:
    <<: *airflow-common
    command: db migrate && 
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: true
      _AIRFLOW_WWW_USER_CREATE: true
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - airflow
    depends_on:
      <<: *airflow-common-depends-on
    networks:
      - lake_net
    
networks:
  lake_net:
    external: true