BrokerCnn:
  host: 127.0.0.1
  port: 9092
  ingest_topics: 
    - sample_topic
  ingest_table: kafka_content
  group_id: ducklake_consumers
  batch_size: 10000


Lake:
  SRC:
    storage:
      sample_minio:
        host: localhost
        port: 9000
        scope: data-source
        secure: false
        region: us-east-1
        style: path
        access_key: minio
        secret: password


    # postgres:
    #   sample_pg_1:
    #     host: localhost
    #     port: 5422
    #     database: postgres
    #     username: postgres
    #     password: password
    #   sample_pg_2:
    #     host: localhost
    #     port: 5423
    #     database: postgres
    #     username: postgres
    #     password: password


  DEST:
    catalog:
      host: localhost
      port: 5433
      database: postgres
      username: postgres
      password: password
      schema: public
      lake_alias: lake

    storage:
      host: localhost
      port: 9000
      scope: destination
      secure: false
      region: us-east-1
      style: path
      access_key: minio
      secret: password
      lake_alias: lake_data

